-- MySQL Script generated by MySQL Workbench
-- Mon May  7 23:59:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema perpus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema perpus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `perpus` DEFAULT CHARACTER SET utf8 ;
USE `perpus` ;

-- -----------------------------------------------------
-- Table `perpus`.`pengarang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perpus`.`pengarang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(50) NULL,
  `alamat` VARCHAR(60) NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `id_pengarang` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perpus`.`buku`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perpus`.`buku` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `judul` VARCHAR(100) NULL,
  `pengarang` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pengarang_id` (`pengarang` ASC),
  CONSTRAINT `id_pengarang_fk`
    FOREIGN KEY (`pengarang`)
    REFERENCES `perpus`.`pengarang` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
